# Generated by Django 4.2.10 on 2024-05-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('country', models.CharField(max_length=200, verbose_name='страна')),
                ('city', models.CharField(max_length=200, verbose_name='город')),
                ('street', models.CharField(max_length=200, verbose_name='улица')),
                ('number_home', models.IntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контактные данные',
                'verbose_name_plural': 'контактные данные',
            },
        ),
        migrations.CreateModel(
            name='ElectronicsFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.contact', verbose_name='контактные данные')),
            ],
            options={
                'verbose_name': 'завод',
                'verbose_name_plural': 'заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('product_model', models.CharField(max_length=100, verbose_name='модель')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название розничной сети')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.contact', verbose_name='контактные данные')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.product', verbose_name='продукт')),
                ('provider_from_factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.electronicsfactory', verbose_name='поставки с завода')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
            },
        ),
        migrations.CreateModel(
            name='SoleTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название и предпринимателя')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.contact', verbose_name='контактные данные')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.product', verbose_name='продукт')),
                ('provider_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network_platform.electronicsfactory', verbose_name='поставки с завода')),
                ('provider_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network_platform.retailnetwork', verbose_name='поставки с розничной сети')),
            ],
            options={
                'verbose_name': 'индивидуальный предприниматель',
                'verbose_name_plural': 'индивидуальные предприниматели',
            },
        ),
        migrations.AddField(
            model_name='electronicsfactory',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_platform.product', verbose_name='продукт'),
        ),
    ]
