# Generated by Django 4.2.10 on 2024-05-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicsfactory',
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='electronicsfactory',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='retailnetwork',
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='retailnetwork',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='soletrader',
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='soletrader',
            old_name='products',
            new_name='product',
        ),
    ]
