# Generated by Django 4.2.10 on 2024-05-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_platform', '0002_rename_contacts_electronicsfactory_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailnetwork',
            old_name='provider_from_factory',
            new_name='provider_factory',
        ),
    ]
