# Generated by Django 4.2.10 on 2024-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_platform', '0003_rename_provider_from_factory_retailnetwork_provider_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number_home',
            field=models.PositiveIntegerField(verbose_name='номер дома'),
        ),
    ]
